services:
  app:
    container_name: headhunter-automation
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
    command: python main.py
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: >
        python -c "import os,socket,sys; s=socket.socket(); s.settimeout(2);
        sys.exit(0) if not s.connect_ex(('127.0.0.1', int(os.getenv('PORT','8080')))) else sys.exit(1)"
      interval: 30s
      timeout: 3s
      retries: 3

